### ISSUE TITLE
Rg vim integration no longer accepts arguments

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#114]
`:Rg -w myword` no longer works.

**Comment by kaihowl** [comment]
Since the introduction of `shellescape` argument passing was (of course) broken. Since we do want both a simple way to pass strings 'as is' and to also parse arguments, we introduce ! (bang) as a modifier for the `:Rg` command.

Detecting the intended usage is difficult. It will be more robust to let the user signal intent with bang. For example, a detection with checking for `-` in the string to detect arguments will fail if `-` is intended to be searched for. Moreover, distinguishing between a file name and the second, space-separated part of a pattern also makes parsing ambiguous.
