### ISSUE TITLE
tmux invalid option pane-border-lines

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#310]
Ubuntu 20.04 has 3.0a for tmux. Tmux 3.3 and later have this option.

Issues:
- Missing tmux test to detect invalid options
- Tmux too old on Ubuntu

**Comment by kaihowl** [comment]
Other than compiling tmux ourselves or using a PPA for Ubuntu (or a snap) there is no good way to keep tmux on Ubuntu up to date. I do install alacritty with snap but since there is no actual feature from a newer tmux that I require, I will keep running with the officially packaged tmux from Ubuntu.
