### ISSUE TITLE
Carbon does not reveal files outside of current pwd

### ISSUE THREAD

**Issue by kaihowl** [kaihowl/dotfiles#551]

**Comment by kaihowl** [comment]
Remainder of this depends on the outcome of https://github.com/SidOfc/carbon.nvim/issues/126.

**Comment by kaihowl** [comment]
Hey @SidOfc, thanks for taking a look. :)
The approach of changing the root of the buffer is what I have been taking with #561. that works nicely. 
Let me know if you are looking for early testers of the branch or some other help. 
I really like Carbon!

**Comment by SidOfc** [comment]
Awesome, glad you like Carbon :)

The branch is called `insanity` (hehe) and can already be used however, it is some ~30 commits behind master. If you want you could give that a shot and provide feedback. I must add that the documentation in this branch is not up to date either. For example, the `buffer` module has been replaced by a `view` module and various other aspects have changed, but these changes have not been reflected in the docs.

**Comment by kaihowl** [comment]
Wow. The branch -- despite the naming -- looks very sane after a super quick check. It even includes checking for the "right" open view depending on the root of the directory.

**Comment by SidOfc** [comment]
Hmn it's quite odd that `resync_timer` is set to `nil` on line `194` since the only place it's set to `nil` is line `198` within the same callback block of code 🤔 

Maybe it's some edge case where the deferred function still runs before being cleared. I can imagine this being the case when `settings.sync_delay` has a really low value.

Does it still happen when `sync_delay` is set to say, `100`? Otherwise it would require a modification to line `194` to do an additional `if view.resync_timer` check perhaps.

**Comment by kaihowl** [comment]
With the latest and greatest master branch of Carbon, I cannot reproduce the above issue anymore. Will test drive this further today and see if it is ready to integrate.
