### ISSUE TITLE
Installing non-interactive

### ISSUE THREAD

**Issue by KaiHoewelmeyer-TomTom** [kaihowl/dotfiles#59]
When installing on a local machine on Ubuntu 20.04, I have to re-enter the sudo password and confirm the addition of PPAs.

**Comment by kaihowl** [comment]
Found issues: 
Happens when calling `sudo add-apt-repository ppa:neovim-ppa/unstable`.

We don't want to set `--force-confdef` and alike. This should still lead to a question to the user.
Do we want `DEBIAN_FRONTEND=noninteractive` to be set? Probably not: Only for add-apt-repository we see the issue.

Why does this not happen on the GitHub runners? Because the script checks if sys.stdin.isatty returns true.

Side remark: add-apt-repository is missing the `--update` flag to force an update of the cache after the addition of the repository.

**Comment by kaihowl** [comment]
Manually verified on Ubuntu droplet. Installs cleanly without interaction + tests pass.
